### ISSUE TITLE
React-select with createform libraries. How can I handle a multiselect?

### ISSUE THREAD

**Issue by TangoPJ** [jucian0/createform#63]
I'm using a multiselect by react-select library. How can I save the options in my object? 
`{...register('skills.programmingLanguages')}` is not working

```
import { createForm } from '@createform/react';

export const usePersonForm = createForm({
  initialValues: {
    firstName: '',
    lastName: '',
    jobTitle: '',
    skills: {
      programmingLanguages: [],
      frameworks: [],
      specializations: [],
      languages: [],
      otherSkills: [],
    },
  },
});
```

```
<CreatableSelect
  isClearable
  id="programmingLanguages"
  closeMenuOnSelect={false}
  components={animatedComponents}
  isMulti
  options={programmingLanguages}
  // {...register('skills.programmingLanguages')}
/>
```

and of course it's not working reset function

```
<button type="reset" className="base-form__button base-form__button-violet">
  Reset
</button>
```

How can I solve this problem?

I read the doc (https://www.useform.org/using-your-form/custom-components) but it didn't help me
Thank you

**Comment by jucian0** [comment]
Hey @TangoPJ, could you try our last release v3.3.19 and this doc [https://www.useform.org/using-your-form/custom-components](https://www.useform.org/using-your-form/custom-components)

Tell me if it helped you.

**Comment by TangoPJ** [comment]
@jucian0 Thank you, I upgraded the package to the v3.3.19 version and It worked for me :) except reset functionality, I'll research the problem

**Comment by jucian0** [comment]
I'm closing the issue you reported due to inactivity. If you have any doubt, just open the issue again!
